# a docker compose file to start a postgressql image and configure its volumes from the host machine
version: '3.8'
services:
  db:
    image: postgres:13.2
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /tmp
    volumes:
      - ./sql/data:/docker-entrypoint-initdb.d/